name: Docker Build

on: push

jobs:
  DockerBuild:
    name: Build and Test Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build -t neso-solar-consumer .

      - name: Run Tests in Docker
        run: docker run --rm neso-solar-consumer
